export const SET_USER_POSITION = "SET_USER_POSITION";
export const SET_ACTIVE_SECTION = "SET_ACTIVE_SECTION";
export const LOAD_FORM_DATA = "LOAD_FORM_DATA";
export const SET_ACTIVE_USER = "SET_ACTIVE_USER";
export const SET_SECTION_STATE = "SET_SECTION_STATE";
export const UPDATE_SECTION_VALUES = "UPDATE_SECTION_VALUES";
